### ISSUE TITLE
Question about Frame MessageID field

### ISSUE THREAD

**Issue by C47D** [makreft/ldf_parser#1]
Hi,

This is not an issue, but more a question or confirmation. I've seen the `dummy_ldf_for_tests.ldf` file contents and I've noticed that you're using decimal values for the MessageID field on the Frames section. E.g. MessageID of SLAVE1e_01 is 10. Is this number in decimal or hexadecimal?

Regards

**Comment by makreft** [comment]
Hi,
I think it's an integer, so decimal. Following the spec (https://microchipdeveloper.com/lin:protocol-app-ldf) the ID can take a value from 0 to 64.
